import { StatusPill } from "@/components/status-pill";
import type {
  ActionReceiptResponse,
  RuntimePolicyEvidencePackResponse,
} from "@/lib/api";
import { statusLabel, statusTone } from "@/lib/action-status";
import type { EvidenceLedgerRow } from "@/lib/evidence-ledger";
import { compactJson, field, formatDateTime, humanize } from "@/lib/format";

type EvidenceReportProps = {
  evidencePack: RuntimePolicyEvidencePackResponse | undefined;
  receipt: ActionReceiptResponse | undefined;
  row: EvidenceLedgerRow | null;
};

type PrintFact = {
  label: string;
  value: string;
  mono?: boolean;
};

function recordFrom(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

function stringFrom(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function valueFrom(record: Record<string, unknown>, ...keys: string[]): unknown {
  for (const key of keys) {
    const value = record[key];
    if (value != null && value !== "") {
      return value;
    }
  }
  return null;
}

function PrintFactGrid({ facts }: { facts: PrintFact[] }) {
  return (
    <dl className="ev-print-fact-grid">
      {facts.map((fact) => (
        <div key={fact.label}>
          <dt>{fact.label}</dt>
          <dd className={fact.mono ? "mono" : undefined}>{fact.value}</dd>
        </div>
      ))}
    </dl>
  );
}

function PrintJsonBlock({ title, value }: { title: string; value: unknown }) {
  return (
    <section className="ev-print-section">
      <h3>{title}</h3>
      <pre>{compactJson(value)}</pre>
    </section>
  );
}

function shortHash(value: string | null | undefined): string {
  if (!value) {
    return "-";
  }
  return value.length > 28 ? `${value.slice(0, 18)}...${value.slice(-8)}` : value;
}

function PrintBrandHeader({
  documentType,
  status,
}: {
  documentType: string;
  status: string;
}) {
  return (
    <header className="ev-print-brand-header">
      <div className="ev-print-brand">
        {/* eslint-disable-next-line @next/next/no-img-element -- Print-only report needs a plain image element for browser PDF output. */}
        <img src="/zroky.logo.png" alt="Zroky" />
        <div>
          <strong>Zroky</strong>
          <span>Verified Action Control Plane</span>
        </div>
      </div>
      <div className="ev-print-document-type">
        <span>{documentType}</span>
        <StatusPill value={status} label={statusLabel(status)} tone={statusTone(status)} />
      </div>
    </header>
  );
}

function PrintTitleBlock({
  facts,
  title,
}: {
  facts: PrintFact[];
  title: string;
}) {
  return (
    <section className="ev-print-title-block">
      <span>Zroky Evidence Report</span>
      <h1>{title}</h1>
      <PrintFactGrid facts={facts} />
    </section>
  );
}

function PrintProofSeal({
  algorithm,
  evidenceHash,
  receiptDigest,
  signature,
  signingKey,
}: {
  algorithm: string;
  evidenceHash: string;
  receiptDigest?: string;
  signature: string;
  signingKey: string;
}) {
  return (
    <section className="ev-print-proof-seal" aria-label="Print proof seal">
      <div>
        <span>Tamper-evident</span>
        <h2>Proof seal</h2>
      </div>
      <PrintFactGrid
        facts={[
          { label: "Signature", value: signature },
          { label: "Receipt digest", value: receiptDigest ?? "-", mono: true },
          { label: "Evidence hash", value: evidenceHash, mono: true },
          { label: "Hash algorithm", value: algorithm, mono: true },
          { label: "Signing key ID", value: signingKey, mono: true },
        ]}
      />
    </section>
  );
}

function PrintFooter({
  evidenceHash,
  generatedAt,
  schema,
}: {
  evidenceHash: string;
  generatedAt: string;
  schema: string;
}) {
  return (
    <footer className="ev-print-footer">
      <span>Generated by Zroky - {formatDateTime(generatedAt)} - schema {schema}</span>
      <span>{shortHash(evidenceHash)}</span>
      <span className="ev-print-page-number" />
      <span>Confidential evidence artifact</span>
    </footer>
  );
}

function receiptStatus(receipt: ActionReceiptResponse): string {
  const core = receipt.receipt;
  return stringFrom(core.final_status) ?? stringFrom(core.proof_status) ?? "generated";
}

function ReceiptReport({ receipt, row }: { receipt: ActionReceiptResponse; row: EvidenceLedgerRow | null }) {
  const core = receipt.receipt;
  const intent = recordFrom(core.intent);
  const policyDecision = recordFrom(core.policy_decision);
  const runnerExecution = recordFrom(core.runner_execution);
  const verification = recordFrom(core.verification);
  const evidence = recordFrom(core.evidence);
  const finalStatus = receiptStatus(receipt);
  const schema = field(core.schema_version, "zroky.action_receipt.v1");
  const evidenceHash = field(valueFrom(evidence, "evidence_hash") ?? receipt.evidence_hash);
  const hashAlgorithm = field(valueFrom(evidence, "hash_algorithm"), "sha256");

  return (
    <>
      <PrintBrandHeader documentType="Action Receipt" status={finalStatus} />

      <PrintTitleBlock
        title={row?.title ?? receipt.action_id}
        facts={[
          { label: "Action ID", value: receipt.action_id, mono: true },
          { label: "Receipt ID", value: receipt.receipt_id, mono: true },
          { label: "Environment", value: field(core.environment) },
          { label: "Generated", value: formatDateTime(receipt.generated_at) },
          { label: "Agent", value: row?.agentName ?? field(valueFrom(intent, "principal")) },
          { label: "Schema", value: schema },
        ]}
      />

      <PrintProofSeal
        algorithm={hashAlgorithm}
        evidenceHash={evidenceHash}
        receiptDigest={receipt.receipt_digest}
        signature={receipt.signature_valid ? "VALID" : "INVALID"}
        signingKey={receipt.signing_key_id}
      />

      <section className="ev-print-section">
        <h2>Action / Intent</h2>
        <PrintFactGrid
          facts={[
            { label: "Action type", value: humanize(stringFrom(intent.action_type) ?? row?.actionType ?? "Protected action") },
            { label: "Operation", value: humanize(stringFrom(intent.operation_kind)) },
            { label: "Contract", value: field(intent.contract_version) },
            { label: "Intent digest", value: field(intent.intent_digest), mono: true },
          ]}
        />
      </section>

      <PrintJsonBlock title="Intent Details" value={{ purpose: intent.purpose, resource: intent.resource, parameters: intent.parameters }} />
      <PrintJsonBlock title="Policy Decision" value={policyDecision} />
      <PrintJsonBlock title="Runner Execution" value={runnerExecution} />
      <PrintJsonBlock title="Verification" value={verification} />
      <PrintJsonBlock title="Timeline" value={core.timeline} />

      <PrintFooter evidenceHash={evidenceHash} generatedAt={receipt.generated_at} schema={schema} />
    </>
  );
}

function EvidencePackReport({ pack, row }: { pack: RuntimePolicyEvidencePackResponse; row: EvidenceLedgerRow | null }) {
  return (
    <>
      <PrintBrandHeader documentType="Evidence Pack" status={pack.verification_status} />

      <PrintTitleBlock
        title={row?.title ?? pack.decision_id}
        facts={[
          { label: "Decision ID", value: pack.decision_id, mono: true },
          { label: "Generated", value: formatDateTime(pack.generated_at) },
          { label: "Agent", value: row?.agentName ?? field(pack.decision.agent_name) },
          { label: "Environment", value: "-" },
          { label: "Schema", value: pack.schema_version },
          { label: "Verification", value: statusLabel(pack.verification_status) },
        ]}
      />

      <PrintProofSeal
        algorithm={pack.hash_algorithm}
        evidenceHash={pack.evidence_hash}
        signature={pack.verification_status === "pass" ? "VALID" : "REVIEW"}
        signingKey="-"
      />

      <section className="ev-print-section">
        <h2>Policy decision</h2>
        <PrintFactGrid
          facts={[
            { label: "Decision", value: humanize(pack.decision.decision) },
            { label: "Status", value: humanize(pack.decision.status) },
            { label: "Tool", value: field(pack.decision.tool_name) },
            { label: "Trace ID", value: field(pack.decision.trace_id), mono: true },
            { label: "Call ID", value: field(pack.decision.call_id), mono: true },
            { label: "Resolved by", value: field(pack.decision.resolved_by) },
            { label: "Resolved", value: formatDateTime(pack.decision.resolved_at) },
            { label: "Approval scope", value: field(pack.decision.approval_scope_hash), mono: true },
          ]}
        />
      </section>

      <PrintJsonBlock title="Mandate Snapshot" value={pack.decision.policy_snapshot} />
      <PrintJsonBlock title="Approval Audit" value={pack.audit_log} />
      <PrintJsonBlock title="Outcome Reconciliation" value={pack.outcome_reconciliation} />

      <PrintFooter evidenceHash={pack.evidence_hash} generatedAt={pack.generated_at} schema={pack.schema_version} />
    </>
  );
}

export function EvidenceReport({ evidencePack, receipt, row }: EvidenceReportProps) {
  if (!row || (!receipt && !evidencePack)) {
    return null;
  }
  return (
    <section className="ev-print-report" aria-label="Printable evidence report">
      {receipt ? <ReceiptReport receipt={receipt} row={row} /> : null}
      {!receipt && evidencePack ? <EvidencePackReport pack={evidencePack} row={row} /> : null}
    </section>
  );
}
