from __future__ import annotations

from app.services._action_pack_types import ActionContractTemplate, ActionPackDefinition


def _support_schema(
    *,
    resource_required: tuple[str, ...],
    parameter_required: tuple[str, ...],
    parameter_properties: dict[str, object] | None = None,
) -> dict[str, object]:
    return {
        "type": "object",
        "required": ["resource", "parameters"],
        "properties": {
            "resource": {
                "type": "object",
                "required": list(resource_required),
                "properties": {
                    "customer_id": {"type": "string", "minLength": 1},
                    "account_id": {"type": "string"},
                    "refund_id": {"type": "string", "minLength": 1},
                    "subscription_id": {"type": "string", "minLength": 1},
                    "ticket_id": {"type": "string", "minLength": 1},
                    "message_id": {"type": "string"},
                    "identity_id": {"type": "string"},
                    "export_id": {"type": "string"},
                    "provider": {"type": "string"},
                },
                "additionalProperties": True,
            },
            "parameters": {
                "type": "object",
                "required": list(parameter_required),
                "properties": {
                    "amount_minor": {"type": "integer", "minimum": 1},
                    "currency": {"type": "string", "minLength": 3, "maxLength": 3},
                    "role": {"type": "string", "minLength": 1},
                    "status": {"type": "string", "minLength": 1},
                    "fields": {
                        "type": "object",
                        "minProperties": 1,
                        "additionalProperties": True,
                    },
                    "reason": {"type": "string"},
                    "channel": {"type": "string"},
                    "recipient": {"type": "string"},
                    "body": {"type": "string"},
                    "coupon_code": {"type": "string"},
                    "credit_amount_minor": {"type": "integer", "minimum": 1},
                    "new_email": {"type": "string"},
                    "new_phone": {"type": "string"},
                    "export_scope": {"type": "string"},
                    "count": {"type": "integer", "minimum": 1},
                    **(parameter_properties or {}),
                },
                "additionalProperties": True,
            },
        },
        "additionalProperties": False,
    }


def _support_contract(
    *,
    contract_key: str,
    operation_kind: str,
    risk_class: str,
    connector_family: str,
    resource_required: tuple[str, ...],
    parameter_required: tuple[str, ...],
    source_of_record: str,
    approval_policy: str,
    positive_assertions: tuple[str, ...],
    parameter_properties: dict[str, object] | None = None,
) -> ActionContractTemplate:
    return ActionContractTemplate(
        contract_key=contract_key,
        version="1.0",
        action_type=contract_key,
        operation_kind=operation_kind,
        domain_family="customer_operations",
        risk_class=risk_class,
        connector_family=connector_family,
        schema=_support_schema(
            resource_required=resource_required,
            parameter_required=parameter_required,
            parameter_properties=parameter_properties,
        ),
        verification_profile={
            "minimum_level": "V4" if risk_class in {"R3", "R4"} else "V3",
            "source_of_record": source_of_record,
            "positive_assertions": list(positive_assertions),
            "approval_policy": approval_policy,
        },
    )


SUPPORT_OPS_PACK = ActionPackDefinition(
    id="support-ops-v1",
    display_name="Support operations",
    summary=(
        "Guard support-agent actions that touch refunds, access, accounts, "
        "subscriptions, tickets, customer messages, identity, and exports."
    ),
    primary_runtime_path="sdk",
    recommended_connectors=(
        "ledger_refund",
        "crm_record",
        "zendesk_ticket",
        "ticket_status",
        "customer_identity",
        "subscription_billing",
        "email_delivery",
        "generic_rest",
        "slack_approval_alert",
    ),
    native_tool_families=(
        "stripe_refund",
        "razorpay_refund",
        "hubspot_customer",
        "salesforce_customer",
        "zendesk_ticket",
        "intercom",
        "sendgrid_email",
        "generic_rest_action",
    ),
    quickstart_steps=(
        "Install support-ops-v1 for the tenant.",
        "Connect Stripe/Razorpay, HubSpot/CRM, Zendesk/Intercom, identity, and Slack where needed.",
        "Call protect() before refund, access, subscription, ticket, message, identity, or export actions.",
        "Verify outcome from saved connectors and publish evidence packs.",
    ),
    contract_templates=(
        ActionContractTemplate(
            contract_key="customer.refund.transfer",
            version="1.0",
            action_type="refund",
            operation_kind="TRANSFER",
            domain_family="customer_operations",
            risk_class="R3",
            connector_family="ledger_refund",
            schema={
                "type": "object",
                "required": ["resource", "parameters"],
                "properties": {
                    "resource": {
                        "type": "object",
                        "required": ["refund_id"],
                        "properties": {
                            "refund_id": {"type": "string", "minLength": 1},
                            "order_id": {"type": "string"},
                            "customer_id": {"type": "string"},
                            "account_id": {"type": "string"},
                            "provider": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                    "parameters": {
                        "type": "object",
                        "required": ["amount_minor", "currency"],
                        "properties": {
                            "amount_minor": {"type": "integer", "minimum": 1},
                            "currency": {"type": "string", "minLength": 3, "maxLength": 3},
                            "reason": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                },
                "additionalProperties": False,
            },
            verification_profile={
                "minimum_level": "V4",
                "source_of_record": "ledger_refund",
                "positive_assertions": [
                    "equals(refund_id)",
                    "equals(amount_minor)",
                    "equals(currency)",
                    "one_of(status, posted, succeeded, captured)",
                ],
                "approval_policy": "dashboard_or_slack_required_for_r3",
            },
        ),
        _support_contract(
            contract_key="customer.refund.create",
            operation_kind="TRANSFER",
            risk_class="R3",
            connector_family="ledger_refund",
            resource_required=("refund_id",),
            parameter_required=("amount_minor", "currency"),
            source_of_record="ledger_refund",
            positive_assertions=(
                "equals(refund_id)",
                "equals(amount_minor)",
                "equals(currency)",
                "one_of(status, posted, succeeded, captured)",
            ),
            approval_policy="dashboard_or_slack_required_for_r3",
        ),
        _support_contract(
            contract_key="customer.refund.cancel",
            operation_kind="TRANSFER",
            risk_class="R3",
            connector_family="ledger_refund",
            resource_required=("refund_id",),
            parameter_required=("reason",),
            source_of_record="ledger_refund",
            positive_assertions=(
                "equals(refund_id)",
                "one_of(status, canceled, failed, voided)",
                "record_updated_after(action_created_at)",
            ),
            approval_policy="dashboard_or_slack_required_for_r3",
        ),
        _support_contract(
            contract_key="customer.access.grant",
            operation_kind="UPDATE",
            risk_class="R3",
            connector_family="customer_identity",
            resource_required=("customer_id",),
            parameter_required=("role",),
            source_of_record="customer_identity",
            positive_assertions=("equals(customer_id)", "role_present(role)", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_required_for_access_change",
        ),
        _support_contract(
            contract_key="customer.access.revoke",
            operation_kind="UPDATE",
            risk_class="R3",
            connector_family="customer_identity",
            resource_required=("customer_id",),
            parameter_required=("role",),
            source_of_record="customer_identity",
            positive_assertions=("equals(customer_id)", "role_absent(role)", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_required_for_access_change",
        ),
        ActionContractTemplate(
            contract_key="customer.record.update",
            version="1.0",
            action_type="customer_record_update",
            operation_kind="UPDATE",
            domain_family="customer_operations",
            risk_class="R2",
            connector_family="crm_record",
            schema={
                "type": "object",
                "required": ["resource", "parameters"],
                "properties": {
                    "resource": {
                        "type": "object",
                        "required": ["customer_id"],
                        "properties": {
                            "customer_id": {"type": "string", "minLength": 1},
                            "account_id": {"type": "string"},
                            "crm_object": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                    "parameters": {
                        "type": "object",
                        "required": ["fields"],
                        "properties": {
                            "fields": {
                                "type": "object",
                                "minProperties": 1,
                                "additionalProperties": True,
                            },
                            "reason": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                },
                "additionalProperties": False,
            },
            verification_profile={
                "minimum_level": "V3",
                "source_of_record": "crm_record",
                "positive_assertions": [
                    "equals(customer_id)",
                    "equals(updated_fields)",
                    "record_updated_after(action_created_at)",
                ],
                "approval_policy": "dashboard_required_when_sensitive_fields_change",
            },
        ),
        _support_contract(
            contract_key="customer.account.status.change",
            operation_kind="UPDATE",
            risk_class="R3",
            connector_family="crm_record",
            resource_required=("customer_id",),
            parameter_required=("status",),
            source_of_record="crm_record",
            positive_assertions=("equals(customer_id)", "equals(status)", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_required_when_customer_state_changes",
        ),
        _support_contract(
            contract_key="customer.subscription.pause",
            operation_kind="UPDATE",
            risk_class="R3",
            connector_family="subscription_billing",
            resource_required=("subscription_id",),
            parameter_required=("reason",),
            source_of_record="subscription_billing",
            positive_assertions=("equals(subscription_id)", "one_of(status, paused, pausing)", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_or_slack_required_for_subscription_change",
        ),
        _support_contract(
            contract_key="customer.subscription.cancel",
            operation_kind="UPDATE",
            risk_class="R3",
            connector_family="subscription_billing",
            resource_required=("subscription_id",),
            parameter_required=("reason",),
            source_of_record="subscription_billing",
            positive_assertions=("equals(subscription_id)", "one_of(status, canceled, canceling)", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_or_slack_required_for_subscription_change",
        ),
        _support_contract(
            contract_key="customer.subscription.reactivate",
            operation_kind="UPDATE",
            risk_class="R3",
            connector_family="subscription_billing",
            resource_required=("subscription_id",),
            parameter_required=("reason",),
            source_of_record="subscription_billing",
            positive_assertions=("equals(subscription_id)", "one_of(status, active, trialing)", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_or_slack_required_for_subscription_change",
        ),
        _support_contract(
            contract_key="support.ticket.close",
            operation_kind="UPDATE",
            risk_class="R2",
            connector_family="zendesk_ticket",
            resource_required=("ticket_id",),
            parameter_required=("reason",),
            source_of_record="zendesk_ticket",
            positive_assertions=("equals(ticket_id)", "one_of(status, solved, closed)", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_required_when_ticket_has_open_risk",
        ),
        _support_contract(
            contract_key="support.ticket.escalate",
            operation_kind="UPDATE",
            risk_class="R2",
            connector_family="zendesk_ticket",
            resource_required=("ticket_id",),
            parameter_required=("reason",),
            source_of_record="zendesk_ticket",
            positive_assertions=("equals(ticket_id)", "priority_or_group_changed", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_required_when_ticket_has_open_risk",
        ),
        _support_contract(
            contract_key="customer.message.send",
            operation_kind="SEND",
            risk_class="R2",
            connector_family="email_delivery",
            resource_required=("customer_id",),
            parameter_required=("channel", "recipient", "body"),
            source_of_record="email_delivery",
            positive_assertions=("equals(recipient)", "delivery_status_recorded", "message_created_after(action_created_at)"),
            approval_policy="dashboard_required_for_external_customer_message",
        ),
        _support_contract(
            contract_key="customer.coupon.issue",
            operation_kind="TRANSFER",
            risk_class="R2",
            connector_family="subscription_billing",
            resource_required=("customer_id",),
            parameter_required=("coupon_code",),
            source_of_record="subscription_billing",
            positive_assertions=("equals(customer_id)", "equals(coupon_code)", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_required_for_customer_credit",
        ),
        _support_contract(
            contract_key="customer.credit.issue",
            operation_kind="TRANSFER",
            risk_class="R3",
            connector_family="subscription_billing",
            resource_required=("customer_id",),
            parameter_required=("credit_amount_minor", "currency"),
            source_of_record="subscription_billing",
            positive_assertions=("equals(customer_id)", "equals(credit_amount_minor)", "equals(currency)"),
            approval_policy="dashboard_or_slack_required_for_customer_credit",
        ),
        _support_contract(
            contract_key="customer.identity.email.change",
            operation_kind="UPDATE",
            risk_class="R3",
            connector_family="customer_identity",
            resource_required=("customer_id",),
            parameter_required=("new_email",),
            source_of_record="customer_identity",
            positive_assertions=("equals(customer_id)", "equals(new_email)", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_required_for_identity_change",
        ),
        _support_contract(
            contract_key="customer.identity.phone.change",
            operation_kind="UPDATE",
            risk_class="R3",
            connector_family="customer_identity",
            resource_required=("customer_id",),
            parameter_required=("new_phone",),
            source_of_record="customer_identity",
            positive_assertions=("equals(customer_id)", "equals(new_phone)", "record_updated_after(action_created_at)"),
            approval_policy="dashboard_required_for_identity_change",
        ),
        _support_contract(
            contract_key="customer.data.export",
            operation_kind="EXPORT",
            risk_class="R4",
            connector_family="generic_rest",
            resource_required=("customer_id",),
            parameter_required=("export_scope",),
            source_of_record="generic_rest",
            positive_assertions=("equals(customer_id)", "export_scope_recorded", "receipt_contains_export_reason"),
            approval_policy="dashboard_or_slack_required_for_r4",
        ),
        _support_contract(
            contract_key="customer.bulk.read",
            operation_kind="READ_SENSITIVE",
            risk_class="R2",
            connector_family="crm_record",
            resource_required=("customer_id",),
            parameter_required=("count",),
            source_of_record="crm_record",
            positive_assertions=("read_scope_recorded", "count_within_declared_scope", "sequence_context_linked"),
            approval_policy="sequence_risk_watch",
        ),
    ),
)


DEVOPS_PACK = ActionPackDefinition(
    id="devops-release-v1",
    display_name="DevOps release control",
    summary=(
        "Guard deploy or infrastructure changes with CI verification, "
        "human approval, and auditable evidence."
    ),
    primary_runtime_path="sdk",
    recommended_connectors=("github_ci", "generic_rest", "slack_approval_alert"),
    native_tool_families=("github_pr_ci_deploy",),
    quickstart_steps=(
        "Install devops-release-v1 for the tenant.",
        "Connect CI/deploy source of record.",
        "Call protect() before deploy or infra change.",
        "Require CI proof and owner approval before release.",
    ),
    contract_templates=(
        ActionContractTemplate(
            contract_key="devops.deploy.change",
            version="1.0",
            action_type="deploy_change",
            operation_kind="DEPLOY",
            domain_family="devops",
            risk_class="R4",
            connector_family="github_ci",
            schema={
                "type": "object",
                "required": ["resource", "parameters"],
                "properties": {
                    "resource": {
                        "type": "object",
                        "required": ["repository", "environment"],
                        "properties": {
                            "repository": {"type": "string", "minLength": 1},
                            "environment": {"type": "string", "minLength": 1},
                            "pull_request": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                    "parameters": {
                        "type": "object",
                        "required": ["head_sha"],
                        "properties": {
                            "head_sha": {"type": "string", "minLength": 7},
                            "base_sha": {"type": "string"},
                            "change_summary": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                },
                "additionalProperties": False,
            },
            verification_profile={
                "minimum_level": "V4",
                "source_of_record": "github_ci",
                "positive_assertions": [
                    "ci_checks_passed(head_sha)",
                    "deployment_environment_matches(environment)",
                    "approval_linked_before_deploy",
                ],
                "approval_policy": "dashboard_or_slack_required_for_r4",
            },
        ),
    ),
)


ECOMMERCE_OPS_PACK = ActionPackDefinition(
    id="ecommerce-ops-v1",
    display_name="Ecommerce operations",
    summary=(
        "Guard order cancellations, inventory adjustments, and customer "
        "discounts with approval, source-of-record verification, and evidence."
    ),
    primary_runtime_path="sdk",
    recommended_connectors=("order_management", "inventory_system", "commerce_platform", "slack_approval_alert"),
    native_tool_families=("shopify_admin", "woocommerce_store", "generic_commerce"),
    quickstart_steps=(
        "Install ecommerce-ops-v1 for the tenant.",
        "Configure Shopify Admin or commerce source-of-record connector.",
        "Call protect() before order cancel, inventory adjust, or discount issue.",
        "Verify order/customer/inventory state before marking outcome verified.",
    ),
    contract_templates=(
        ActionContractTemplate(
            contract_key="commerce.order.cancel",
            version="1.0",
            action_type="order_cancel",
            operation_kind="UPDATE",
            domain_family="ecommerce_operations",
            risk_class="R3",
            connector_family="order_management",
            schema={
                "type": "object",
                "required": ["resource", "parameters"],
                "properties": {
                    "resource": {
                        "type": "object",
                        "required": ["order_id"],
                        "properties": {
                            "order_id": {"type": "string", "minLength": 1},
                            "customer_id": {"type": "string"},
                            "channel": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                    "parameters": {
                        "type": "object",
                        "required": ["reason"],
                        "properties": {
                            "reason": {"type": "string", "minLength": 1},
                            "restock": {"type": "boolean"},
                        },
                        "additionalProperties": True,
                    },
                },
                "additionalProperties": False,
            },
            verification_profile={
                "minimum_level": "V4",
                "source_of_record": "order_management",
                "positive_assertions": [
                    "equals(order_id)",
                    "one_of(status, cancelled, canceled, voided)",
                    "record_updated_after(action_created_at)",
                ],
                "approval_policy": "dashboard_or_slack_required_for_r3",
            },
        ),
        ActionContractTemplate(
            contract_key="commerce.inventory.adjust",
            version="1.0",
            action_type="inventory_adjust",
            operation_kind="UPDATE",
            domain_family="ecommerce_operations",
            risk_class="R2",
            connector_family="inventory_system",
            schema={
                "type": "object",
                "required": ["resource", "parameters"],
                "properties": {
                    "resource": {
                        "type": "object",
                        "required": ["sku"],
                        "properties": {
                            "sku": {"type": "string", "minLength": 1},
                            "location_id": {"type": "string"},
                            "warehouse": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                    "parameters": {
                        "type": "object",
                        "required": ["quantity_delta"],
                        "properties": {
                            "quantity_delta": {"type": "integer"},
                            "reason": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                },
                "additionalProperties": False,
            },
            verification_profile={
                "minimum_level": "V3",
                "source_of_record": "inventory_system",
                "positive_assertions": [
                    "equals(sku)",
                    "inventory_reflects(quantity_delta)",
                    "record_updated_after(action_created_at)",
                ],
                "approval_policy": "dashboard_required_when_large_adjustment",
            },
        ),
        ActionContractTemplate(
            contract_key="commerce.discount.issue",
            version="1.0",
            action_type="discount_issue",
            operation_kind="TRANSFER",
            domain_family="ecommerce_operations",
            risk_class="R3",
            connector_family="commerce_platform",
            schema={
                "type": "object",
                "required": ["resource", "parameters"],
                "properties": {
                    "resource": {
                        "type": "object",
                        "required": ["customer_id"],
                        "properties": {
                            "customer_id": {"type": "string", "minLength": 1},
                            "order_id": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                    "parameters": {
                        "type": "object",
                        "required": ["amount_minor", "currency"],
                        "properties": {
                            "amount_minor": {"type": "integer", "minimum": 1},
                            "currency": {"type": "string", "minLength": 3, "maxLength": 3},
                            "code": {"type": "string"},
                        },
                        "additionalProperties": True,
                    },
                },
                "additionalProperties": False,
            },
            verification_profile={
                "minimum_level": "V4",
                "source_of_record": "commerce_platform",
                "positive_assertions": [
                    "equals(customer_id)",
                    "equals(amount_minor)",
                    "equals(currency)",
                    "discount_active(code)",
                ],
                "approval_policy": "dashboard_or_slack_required_for_r3",
            },
        ),
    ),
)
