from __future__ import annotations

from app.services._tool_registry_types import ALL_LAUNCH_ACTION_TYPES, ToolRegistryItem


NATIVE_TOOL_FAMILIES: tuple[ToolRegistryItem, ...] = (
    ToolRegistryItem(
        id="stripe_refund",
        kind="native_tool_family",
        label="Stripe refunds",
        description="Guard and execute Stripe refund actions through the customer-hosted runner, then verify source-of-record state.",
        category="payments",
        implementation_status="available",
        supported_action_types=("refund", "payment_adjustment"),
        recommended_for_action_types=("refund",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="runner_adapter.stripe_refund",
        availability_notes="Available in the Python customer-hosted runner; managed-hosted execution packaging is still pending.",
    ),
    ToolRegistryItem(
        id="razorpay_refund",
        kind="native_tool_family",
        label="Razorpay refunds",
        description="Guard and verify Razorpay refund actions through a customer-hosted runner and saved Razorpay read verifier.",
        category="payments",
        implementation_status="template",
        launch_tier="p1",
        supported_action_types=("refund", "payment_adjustment"),
        recommended_for_action_types=("refund",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.razorpay_refund",
    ),
    ToolRegistryItem(
        id="stripe_payment",
        kind="native_tool_family",
        label="Stripe payments",
        description="Guard payment-status and payout workflows, then verify PaymentIntent state through Stripe.",
        category="payments",
        implementation_status="available",
        launch_tier="p0",
        supported_action_types=("payment_adjustment", "vendor_payout", "invoice_spend_approval"),
        recommended_for_action_types=("payment_adjustment", "vendor_payout"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.stripe_payment",
    ),
    ToolRegistryItem(
        id="shopify_admin",
        kind="native_tool_family",
        label="Shopify Admin",
        description="Guard commerce actions and verify order state through Shopify Admin API evidence.",
        category="commerce",
        implementation_status="available",
        launch_tier="p0",
        supported_action_types=("order_cancel", "inventory_adjust", "discount_issue"),
        recommended_for_action_types=("order_cancel", "inventory_adjust", "discount_issue"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.shopify_admin",
    ),
    ToolRegistryItem(
        id="hubspot_customer",
        kind="native_tool_family",
        label="HubSpot customer records",
        description="Template for customer/contact record update verification in HubSpot.",
        category="crm",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("customer_record_update",),
        recommended_for_action_types=("customer_record_update",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="salesforce_customer",
        kind="native_tool_family",
        label="Salesforce customer records",
        description="Template for customer/account/contact update verification in Salesforce.",
        category="crm",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("customer_record_update",),
        recommended_for_action_types=("customer_record_update",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="zendesk_ticket",
        kind="native_tool_family",
        label="Zendesk tickets",
        description="Template for ticket close/status verification in Zendesk.",
        category="support",
        implementation_status="planned",
        supported_action_types=("ticket_close",),
        recommended_for_action_types=("ticket_close",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="freshdesk_ticket",
        kind="native_tool_family",
        label="Freshdesk tickets",
        description="Template for ticket close/status verification in Freshdesk.",
        category="support",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("ticket_close",),
        recommended_for_action_types=("ticket_close",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="sendgrid_email",
        kind="native_tool_family",
        label="SendGrid email",
        description="Template for email send and delivery verification through SendGrid.",
        category="messaging",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("email_send",),
        recommended_for_action_types=("email_send",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="gmail_email",
        kind="native_tool_family",
        label="Gmail email",
        description="Template for email send verification through Gmail or Google Workspace.",
        category="messaging",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("email_send",),
        recommended_for_action_types=("email_send",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="github_pr_ci_deploy",
        kind="native_tool_family",
        label="GitHub PR, CI, and deploy",
        description="Template for repository, check-run, and deployment outcome verification.",
        category="devops",
        implementation_status="template",
        supported_action_types=("deploy_change",),
        recommended_for_action_types=("deploy_change",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="slack_approval_alert",
        kind="native_tool_family",
        label="Slack approval and alert",
        description="Approval and alert surface for held actions; not a proof source unless message delivery is verified.",
        category="approval",
        implementation_status="available",
        supported_action_types=("refund", "payment_adjustment", "customer_record_update", "ticket_close", "email_send", "deploy_change", "invoice_spend_approval", "internal_api_mutation", "database_record_update", "custom"),
        recommended_for_action_types=("refund", "invoice_spend_approval", "deploy_change"),
        requires_customer_credentials=True,
        dashboard_href="/integrations/slack",
        backend_capability="slack.approval_alert",
    ),
    ToolRegistryItem(
        id="zroky_dashboard_approval",
        kind="native_tool_family",
        label="Zroky dashboard approvals",
        description="First-party approval surface for exact intent-digest-bound approve/reject decisions.",
        category="approval",
        implementation_status="available",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        recommended_for_action_types=("refund", "customer_record_update", "deploy_change", "internal_api_mutation"),
        requires_customer_credentials=False,
        dashboard_href="/approvals",
        backend_capability="approvals.dashboard",
    ),
    ToolRegistryItem(
        id="generic_rest_action",
        kind="native_tool_family",
        label="Generic REST protected action",
        description="Execute approved internal API or workflow actions through the customer-hosted runner.",
        category="execution",
        implementation_status="available",
        supported_action_types=("customer_record_update", "email_send", "internal_api_mutation", "custom"),
        recommended_for_action_types=("internal_api_mutation", "custom"),
        requires_customer_credentials=True,
        dashboard_href="/settings/keys",
        backend_capability="runner_adapter.generic_rest",
    ),
    ToolRegistryItem(
        id="custom_python_agent",
        kind="native_tool_family",
        label="Custom Python agents",
        description="Python agents using the Zroky SDK, protected runner, and saved connector verification helpers.",
        category="agent_framework",
        implementation_status="available",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        recommended_for_action_types=("refund", "internal_api_mutation", "custom"),
        dashboard_href="/settings/keys",
        backend_capability="sdk.python",
    ),
    ToolRegistryItem(
        id="custom_typescript_agent",
        kind="native_tool_family",
        label="Custom TypeScript agents",
        description="TypeScript agents using the Zroky JS SDK for policy guard and outcome verification.",
        category="agent_framework",
        implementation_status="available",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        recommended_for_action_types=("internal_api_mutation", "custom"),
        dashboard_href="/settings/keys",
        backend_capability="sdk.typescript",
    ),
    ToolRegistryItem(
        id="openai_agents_sdk",
        kind="native_tool_family",
        label="OpenAI Agents SDK",
        description="Template connector for wrapping OpenAI Agents SDK tool calls with Zroky action contracts.",
        category="agent_framework",
        implementation_status="template",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        recommended_for_action_types=("internal_api_mutation", "custom"),
        dashboard_href="/settings/keys",
        availability_notes="Use SDK guard/verify helpers today; framework-specific example polish remains pending.",
    ),
    ToolRegistryItem(
        id="langgraph",
        kind="native_tool_family",
        label="LangGraph",
        description="Template connector for routing LangGraph node/tool actions through Zroky policy and receipt workflows.",
        category="agent_framework",
        implementation_status="template",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        recommended_for_action_types=("refund", "internal_api_mutation", "custom"),
        dashboard_href="/settings/keys",
        availability_notes="Python integration path exists through the SDK; dedicated LangGraph examples remain pending.",
    ),
    ToolRegistryItem(
        id="openai_llm",
        kind="native_tool_family",
        label="OpenAI",
        description="LLM provider context for agents whose protected tool calls are guarded by Zroky.",
        category="llm_provider",
        implementation_status="template",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        launch_tier="p0",
        dashboard_href="/settings/providers",
    ),
    ToolRegistryItem(
        id="anthropic_llm",
        kind="native_tool_family",
        label="Anthropic",
        description="LLM provider context for agents whose protected tool calls are guarded by Zroky.",
        category="llm_provider",
        implementation_status="template",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        launch_tier="p0",
        dashboard_href="/settings/providers",
    ),
    ToolRegistryItem(
        id="azure_openai_llm",
        kind="native_tool_family",
        label="Azure OpenAI",
        description="Enterprise OpenAI deployment context for protected agent actions.",
        category="llm_provider",
        implementation_status="template",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        launch_tier="p0",
        dashboard_href="/settings/providers",
    ),
    ToolRegistryItem(
        id="google_gemini_llm",
        kind="native_tool_family",
        label="Google Gemini",
        description="LLM provider context for Gemini-backed agents guarded by Zroky.",
        category="llm_provider",
        implementation_status="template",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        launch_tier="p0",
        dashboard_href="/settings/providers",
    ),
    ToolRegistryItem(
        id="litellm_gateway",
        kind="native_tool_family",
        label="LiteLLM gateway",
        description="Gateway context for teams routing multiple model providers while Zroky controls high-risk actions.",
        category="llm_gateway",
        implementation_status="template",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        launch_tier="p0",
        dashboard_href="/settings/providers",
    ),
    ToolRegistryItem(
        id="sentry",
        kind="native_tool_family",
        label="Sentry",
        description="Production error tracking connector for protected action runner and control-plane failures.",
        category="observability",
        implementation_status="planned",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        launch_tier="p0",
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="posthog",
        kind="native_tool_family",
        label="PostHog",
        description="Product analytics connector for launch usage, approvals, verification outcomes, and bypass visibility.",
        category="observability",
        implementation_status="planned",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        launch_tier="p0",
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="opentelemetry",
        kind="native_tool_family",
        label="OpenTelemetry",
        description="Trace/metric/log context for the protected action control loop.",
        category="observability",
        implementation_status="template",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        launch_tier="p0",
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="crewai",
        kind="native_tool_family",
        label="CrewAI",
        description="Framework template for CrewAI agents whose delegated tools require Zroky approval and receipts.",
        category="agent_framework",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        dashboard_href="/settings/keys",
    ),
    ToolRegistryItem(
        id="autogen",
        kind="native_tool_family",
        label="AutoGen",
        description="Framework template for AutoGen multi-agent tool execution control.",
        category="agent_framework",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        dashboard_href="/settings/keys",
    ),
    ToolRegistryItem(
        id="llamaindex",
        kind="native_tool_family",
        label="LlamaIndex",
        description="Framework template for LlamaIndex agents and workflows that mutate business systems.",
        category="agent_framework",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        dashboard_href="/settings/keys",
    ),
    ToolRegistryItem(
        id="vercel_ai_sdk",
        kind="native_tool_family",
        label="Vercel AI SDK",
        description="TypeScript framework template for protecting tool calls in Vercel AI SDK applications.",
        category="agent_framework",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        dashboard_href="/settings/keys",
    ),
    ToolRegistryItem(
        id="intercom",
        kind="native_tool_family",
        label="Intercom",
        description="Support/customer messaging connector roadmap item for support operations agents.",
        category="support",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("ticket_close", "email_send", "customer_record_update"),
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="linear",
        kind="native_tool_family",
        label="Linear",
        description="Issue/change-management connector roadmap item for DevOps and product operations workflows.",
        category="devops",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("deploy_change", "internal_api_mutation", "custom"),
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="jira",
        kind="native_tool_family",
        label="Jira",
        description="Issue/change-management connector roadmap item for enterprise approval and audit workflows.",
        category="devops",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("deploy_change", "internal_api_mutation", "custom"),
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="gitlab_ci",
        kind="native_tool_family",
        label="GitLab CI",
        description="CI/deployment verifier roadmap item for GitLab-hosted engineering workflows.",
        category="devops",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("deploy_change",),
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="datadog",
        kind="native_tool_family",
        label="Datadog",
        description="Observability connector roadmap item for protected action incidents, traces, and metrics.",
        category="observability",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="grafana_cloud",
        kind="native_tool_family",
        label="Grafana Cloud",
        description="Observability connector roadmap item for action-loop metrics and incident dashboards.",
        category="observability",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="bigquery_read",
        kind="native_tool_family",
        label="BigQuery read verifier",
        description="Warehouse-backed source-of-record verifier roadmap item.",
        category="warehouse_verifier",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("internal_api_mutation", "database_record_update", "custom"),
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="snowflake_read",
        kind="native_tool_family",
        label="Snowflake read verifier",
        description="Warehouse-backed source-of-record verifier roadmap item.",
        category="warehouse_verifier",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=("internal_api_mutation", "database_record_update", "custom"),
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="redis_audit_ingest",
        kind="native_tool_family",
        label="Redis audit ingestion",
        description="Event/audit ingestion roadmap item for mutation streams and bypass detection.",
        category="audit_ingestion",
        implementation_status="planned",
        launch_tier="p1",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        dashboard_href="/integrations",
    ),
    ToolRegistryItem(
        id="connector_marketplace",
        kind="native_tool_family",
        label="Connector marketplace",
        description="Deferred broad marketplace surface; launch should stay focused on first-party critical connectors.",
        category="platform",
        implementation_status="planned",
        launch_tier="p2",
        supported_action_types=ALL_LAUNCH_ACTION_TYPES,
        dashboard_href="/integrations",
    ),
)

