from __future__ import annotations

from app.services._tool_registry_types import ToolRegistryItem


VERIFICATION_CONNECTORS: tuple[ToolRegistryItem, ...] = (
    ToolRegistryItem(
        id="ledger_refund",
        kind="verification_connector",
        label="Ledger / refund verifier",
        description="Verify refund claims against a saved ledger or payment-provider read endpoint.",
        category="system_of_record",
        implementation_status="available",
        supported_action_types=("refund", "payment_adjustment"),
        recommended_for_action_types=("refund", "payment_adjustment"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.ledger_refund_api",
        manifest_id="ledger_refund.v1",
    ),
    ToolRegistryItem(
        id="stripe_refund",
        kind="verification_connector",
        label="Stripe refund verifier",
        description="Read Stripe refund records through the Stripe API for claimed-vs-actual payment proof.",
        category="system_of_record",
        implementation_status="available",
        launch_tier="p1",
        supported_action_types=("refund", "payment_adjustment"),
        recommended_for_action_types=("refund", "payment_adjustment"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.stripe_refund",
        manifest_id="stripe_refund.v1",
        availability_notes="Uses a Stripe restricted secret key with read-only refunds access.",
    ),
    ToolRegistryItem(
        id="crm_record",
        kind="verification_connector",
        label="CRM customer record verifier",
        description="Verify claimed customer, account, or contact record changes against a CRM read endpoint.",
        category="system_of_record",
        implementation_status="available",
        supported_action_types=("customer_record_update",),
        recommended_for_action_types=("customer_record_update",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.customer_record_api",
        manifest_id="crm_record.v1",
    ),
    ToolRegistryItem(
        id="hubspot_crm",
        kind="verification_connector",
        label="HubSpot CRM verifier",
        description="Read HubSpot contact records through the CRM v3 API for claimed-vs-actual verification.",
        category="system_of_record",
        implementation_status="available",
        launch_tier="p1",
        supported_action_types=("customer_record_update",),
        recommended_for_action_types=("customer_record_update",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.hubspot_crm",
        manifest_id="hubspot_crm.v1",
        availability_notes="Uses a HubSpot private app bearer token today; OAuth app install is planned.",
    ),
    ToolRegistryItem(
        id="salesforce_crm",
        kind="verification_connector",
        label="Salesforce CRM verifier",
        description="Read Salesforce sObject records for claimed-vs-actual verification when the customer supplies a working access token.",
        category="system_of_record",
        implementation_status="template",
        launch_tier="p1",
        supported_action_types=("customer_record_update",),
        recommended_for_action_types=("customer_record_update",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.salesforce_crm",
        manifest_id="salesforce_crm.v1",
        availability_notes="Manual bearer-token verification exists, but production OAuth refresh is not launch-grade yet.",
    ),
    ToolRegistryItem(
        id="zoho_crm",
        kind="verification_connector",
        label="Zoho CRM verifier",
        description="Read Zoho CRM module records for claimed-vs-actual verification when an access token is available.",
        category="system_of_record",
        implementation_status="template",
        launch_tier="p1",
        supported_action_types=("customer_record_update",),
        recommended_for_action_types=("customer_record_update",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.zoho_crm",
        manifest_id="zoho_crm.v1",
        availability_notes="OAuth connect UI exists, but refresh-token verification lifecycle still needs launch hardening.",
    ),
    ToolRegistryItem(
        id="ticket_status",
        kind="verification_connector",
        label="Ticket status verifier",
        description="Verify ticket close, escalation, assignment, or status changes in the ticketing system.",
        category="system_of_record",
        implementation_status="planned",
        supported_action_types=("ticket_close",),
        recommended_for_action_types=("ticket_close",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        manifest_id="ticket_status.v1",
    ),
    ToolRegistryItem(
        id="zendesk_ticket",
        kind="verification_connector",
        label="Zendesk ticket verifier",
        description="Read Zendesk Support tickets for claimed-vs-actual verification of support agent actions.",
        category="system_of_record",
        implementation_status="available",
        launch_tier="p1",
        supported_action_types=("ticket_close",),
        recommended_for_action_types=("ticket_close",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.zendesk_ticket",
        manifest_id="zendesk_ticket.v1",
        availability_notes="Supports read-scoped Zendesk OAuth bearer tokens or API token basic auth; one-click OAuth install is planned.",
    ),
    ToolRegistryItem(
        id="jira_issue",
        kind="verification_connector",
        label="Jira / JSM issue verifier",
        description="Read Jira and Jira Service Management issues for claimed-vs-actual verification of support, ITSM, access, and change actions.",
        category="system_of_record",
        implementation_status="available",
        launch_tier="p1",
        supported_action_types=("ticket_close", "internal_api_mutation", "deploy_change"),
        recommended_for_action_types=("ticket_close", "internal_api_mutation"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.jira_issue",
        manifest_id="jira_issue.v1",
        availability_notes="Supports Atlassian email plus API token basic auth today; OAuth app install is planned.",
    ),
    ToolRegistryItem(
        id="servicenow_change",
        kind="verification_connector",
        label="ServiceNow change verifier",
        description="Read ServiceNow change or incident records for claimed-vs-actual ITSM verification.",
        category="system_of_record",
        implementation_status="template",
        launch_tier="p1",
        supported_action_types=("ticket_close", "internal_api_mutation", "deploy_change"),
        recommended_for_action_types=("internal_api_mutation", "deploy_change"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        manifest_id="servicenow_change.v1",
        availability_notes="Manifest preset exists; production OAuth install is not launch-grade yet.",
    ),
    ToolRegistryItem(
        id="razorpay_refund",
        kind="verification_connector",
        label="Razorpay refund verifier",
        description="Read Razorpay refunds for claimed-vs-actual verification of refund and payment-adjustment actions.",
        category="system_of_record",
        implementation_status="available",
        launch_tier="p1",
        supported_action_types=("refund", "payment_adjustment"),
        recommended_for_action_types=("refund", "payment_adjustment"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.razorpay_refund",
        manifest_id="razorpay_refund.v1",
        availability_notes="Supports Razorpay key-id plus key-secret basic auth today; OAuth is not required for server API keys.",
    ),
    ToolRegistryItem(
        id="stripe_payment",
        kind="verification_connector",
        label="Stripe payment verifier",
        description="Read Stripe PaymentIntent records for claimed-vs-actual payment proof.",
        category="system_of_record",
        implementation_status="available",
        launch_tier="p0",
        supported_action_types=("payment_adjustment", "invoice_spend_approval", "vendor_payout", "custom"),
        recommended_for_action_types=("payment_adjustment", "vendor_payout"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.stripe_payment",
        manifest_id="stripe_payment.v1",
        availability_notes="Uses a Stripe restricted secret key with read-only PaymentIntent access.",
    ),
    ToolRegistryItem(
        id="shopify_admin",
        kind="verification_connector",
        label="Shopify Admin verifier",
        description="Read Shopify Admin order records for commerce action proof.",
        category="system_of_record",
        implementation_status="available",
        launch_tier="p0",
        supported_action_types=("order_cancel", "inventory_adjust", "discount_issue", "custom"),
        recommended_for_action_types=("order_cancel", "inventory_adjust", "discount_issue"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.shopify_admin",
        manifest_id="shopify_admin.v1",
        availability_notes="Uses a read-only Shopify Admin API access token.",
    ),
    ToolRegistryItem(
        id="netsuite_finance",
        kind="verification_connector",
        label="NetSuite finance verifier",
        description="Read NetSuite finance and procurement records for claimed-vs-actual verification when the customer supplies a working read token.",
        category="system_of_record",
        implementation_status="template",
        launch_tier="p1",
        supported_action_types=("invoice_spend_approval", "payment_adjustment", "internal_api_mutation", "custom"),
        recommended_for_action_types=("invoice_spend_approval", "payment_adjustment"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.netsuite_finance",
        manifest_id="netsuite_finance.v1",
        availability_notes="Manual read-token verification exists, but production NetSuite TBA/OAuth setup is not launch-grade yet.",
    ),
    ToolRegistryItem(
        id="email_delivery",
        kind="verification_connector",
        label="Email delivery verifier",
        description="Verify that an agent-sent email or provider message was actually accepted or delivered.",
        category="system_of_record",
        implementation_status="planned",
        supported_action_types=("email_send",),
        recommended_for_action_types=("email_send",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        manifest_id="email_delivery.v1",
    ),
    ToolRegistryItem(
        id="github_ci",
        kind="verification_connector",
        label="GitHub CI / deploy verifier",
        description="Verify pull request, check run, deployment, or change-management outcome proof.",
        category="system_of_record",
        implementation_status="planned",
        supported_action_types=("deploy_change",),
        recommended_for_action_types=("deploy_change",),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        manifest_id="github_ci.v1",
    ),
    ToolRegistryItem(
        id="generic_rest",
        kind="verification_connector",
        label="Generic REST/OpenAPI verifier",
        description="Map an internal API read endpoint into expected-vs-observed verification.",
        category="generic_verifier",
        implementation_status="available",
        supported_action_types=("refund", "payment_adjustment", "customer_record_update", "ticket_close", "email_send", "deploy_change", "invoice_spend_approval", "internal_api_mutation", "database_record_update", "custom"),
        recommended_for_action_types=("internal_api_mutation", "custom"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        backend_capability="system_of_record.generic_rest_api",
        manifest_id="generic_rest.v1",
    ),
    ToolRegistryItem(
        id="webhook_callback",
        kind="verification_connector",
        label="Webhook outcome callback",
        description="Accept a customer-signed outcome callback when Zroky cannot read the source system directly.",
        category="generic_verifier",
        implementation_status="template",
        supported_action_types=("refund", "payment_adjustment", "customer_record_update", "ticket_close", "email_send", "deploy_change", "invoice_spend_approval", "internal_api_mutation", "database_record_update", "custom"),
        recommended_for_action_types=("invoice_spend_approval", "custom"),
        requires_customer_credentials=False,
        dashboard_href="/integrations",
        manifest_id="webhook_callback.v1",
    ),
    ToolRegistryItem(
        id="database_read",
        kind="verification_connector",
        label="Database read verifier",
        description="Read a customer database table or view for verification-only outcome proof.",
        category="generic_verifier",
        implementation_status="planned",
        supported_action_types=("customer_record_update", "ticket_close", "email_send", "deploy_change", "invoice_spend_approval", "internal_api_mutation", "database_record_update", "custom"),
        recommended_for_action_types=("database_record_update", "internal_api_mutation"),
        requires_customer_credentials=True,
        dashboard_href="/integrations",
        manifest_id="database_read.v1",
    ),
)


