"""Post-execution verification and receipt generation for MCP tool calls.

This is the Slice-2 bridge from the MCP proxy into the existing verified
actions substrate. It deliberately reuses the normal tables and services:

* ``ActionExecutionAttempt`` records the MCP proxy as the executor.
* ``OutcomeReconciliationCheck`` records SOR verification, or not-verified
  when the upstream tool does not provide independent evidence.
* ``ActionReceipt`` is generated by ``generate_action_receipt`` so signing,
  canonicalization, public-key verification, and billing all stay shared.
"""
from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.db.models import ActionExecutionAttempt, ActionIntent
from app.services.action_kernel import canonical_json, get_action_intent, sha256_digest
from app.services.action_receipts import (
    generate_action_receipt,
    verify_action_receipt_signature,
)
from app.services.action_runner import register_action_runner
from app.services.action_timeline import record_action_timeline_event
from app.services.outcome_reconciliation import ApiRecordConnector, reconcile_outcome
from app.services.protected_action_billing import METER_RUNNER_EXECUTIONS, reserve_usage_meter


MCP_RUNNER_NAME = "zroky-mcp-proxy"
MCP_RUNNER_TYPE = "managed_sandbox"
MCP_CREDENTIAL_REF = "zroky-secret://mcp/proxy"


@dataclass(frozen=True)
class McpPostExecutionResult:
    proof_status: str
    receipt_id: str
    receipt_digest: str
    signature_algorithm: str
    signature_valid: bool

    def to_meta(self) -> dict[str, Any]:
        return {
            "proof_status": self.proof_status,
            "receipt_id": self.receipt_id,
            "receipt_digest": self.receipt_digest,
            "signature_algorithm": self.signature_algorithm,
            "signature_valid": self.signature_valid,
        }


class McpPostExecutionProcessor:
    """Synchronously verify and receipt an allowed MCP tool call."""

    def __init__(self, db: Session, *, actor: str | None = "mcp-proxy") -> None:
        self._db = db
        self._actor = actor

    def process(
        self,
        *,
        project_id: str,
        intent_id: str,
        event_id: str | None,
        tool_name: str,
        arguments: dict[str, Any],
        execution_state: str,
        upstream_result: dict[str, Any] | None,
        upstream_error: str | None,
    ) -> McpPostExecutionResult:
        intent = get_action_intent(self._db, project_id=project_id, action_id=intent_id)
        runner = register_action_runner(
            self._db,
            project_id=project_id,
            name=MCP_RUNNER_NAME,
            runner_type=MCP_RUNNER_TYPE,
            environment=intent.environment,
            supported_operation_kinds=[],
            credential_scope={"default_credential_ref": MCP_CREDENTIAL_REF},
            capability_version="mcp-proxy/v1",
            registered_by_subject=self._actor,
        ).row

        attempt = self._record_execution_attempt(
            intent=intent,
            runner_id=runner.id,
            event_id=event_id,
            tool_name=tool_name,
            arguments=arguments,
            execution_state=execution_state,
            upstream_result=upstream_result,
            upstream_error=upstream_error,
        )
        verification = _verification_hint(upstream_result)
        claimed = _dict_or(verification.get("claimed"), arguments)
        actual = _actual_record(verification)
        connector_type = _text(verification.get("connector_type")) or "mcp_tool_result"
        record_found = verification.get("record_found")
        if record_found is None and actual is not None:
            record_found = True

        metadata: dict[str, Any] = {
            "source": "mcp_proxy",
            "proof_mode": "mcp_post_execution",
            "execution_state": execution_state,
            "tool_name": tool_name,
            "execution_attempt_id": attempt.id,
            "mcp_event_id": event_id,
        }
        if execution_state == "unknown":
            metadata["connector"] = {"retryable": True}
            metadata["upstream_error"] = upstream_error

        outcome = reconcile_outcome(
            self._db,
            project_id=project_id,
            claimed=claimed,
            connector=ApiRecordConnector(
                record=actual,
                record_found=record_found if isinstance(record_found, bool) else None,
                connector_type=connector_type,
            ),
            runtime_policy_decision_id=intent.runtime_policy_decision_id,
            action_type=intent.action_type,
            system_ref=_text(verification.get("system_ref")) or f"mcp:{tool_name}:{intent.id}",
            amount_usd=_float(claimed.get("amount_usd")),
            currency=_text(claimed.get("currency")),
            match_fields=_string_list(verification.get("match_fields")),
            idempotency_key=f"mcp-post-exec:{intent.id}:{event_id or attempt.id}:verify",
            metadata=metadata,
        )

        intent = self._db.execute(
            select(ActionIntent).where(ActionIntent.project_id == project_id, ActionIntent.id == intent_id)
        ).scalar_one()
        intent.proof_status = outcome.verdict
        intent.receipt_status = "pending"
        self._db.add(intent)
        record_action_timeline_event(
            self._db,
            project_id=project_id,
            action_id=intent_id,
            event_type="verification_completed",
            payload={
                "source": "mcp_proxy",
                "outcome_reconciliation_id": outcome.id,
                "verdict": outcome.verdict,
                "execution_attempt_id": attempt.id,
                "mcp_event_id": event_id,
            },
            actor=self._actor,
        )

        generated = generate_action_receipt(
            self._db,
            project_id=project_id,
            action_id=intent_id,
            actor=self._actor,
        )
        self._db.commit()
        return McpPostExecutionResult(
            proof_status=outcome.verdict,
            receipt_id=generated.row.id,
            receipt_digest=generated.row.receipt_digest,
            signature_algorithm=generated.row.signature_algorithm,
            signature_valid=verify_action_receipt_signature(generated.row),
        )

    def _record_execution_attempt(
        self,
        *,
        intent: ActionIntent,
        runner_id: str,
        event_id: str | None,
        tool_name: str,
        arguments: dict[str, Any],
        execution_state: str,
        upstream_result: dict[str, Any] | None,
        upstream_error: str | None,
    ) -> ActionExecutionAttempt:
        existing = self._db.execute(
            select(ActionExecutionAttempt).where(
                ActionExecutionAttempt.project_id == intent.project_id,
                ActionExecutionAttempt.action_intent_id == intent.id,
                ActionExecutionAttempt.idempotency_key == _attempt_idempotency_key(intent.id, event_id),
            )
        ).scalar_one_or_none()
        if existing is not None:
            return existing

        now = datetime.now(timezone.utc)
        attempt_number = int(
            self._db.execute(
                select(func.count(ActionExecutionAttempt.id)).where(
                    ActionExecutionAttempt.project_id == intent.project_id,
                    ActionExecutionAttempt.action_intent_id == intent.id,
                )
            ).scalar_one()
            or 0
        ) + 1
        final_status = "succeeded" if execution_state == "succeeded" else "ambiguous"
        plan_document = {
            "action_intent_id": intent.id,
            "intent_digest": intent.intent_digest,
            "contract_version": f"{intent.contract_key}/{intent.contract_version}",
            "action_type": intent.action_type,
            "operation_kind": intent.operation_kind,
            "environment": intent.environment,
            "runner": {
                "id": runner_id,
                "type": MCP_RUNNER_TYPE,
                "environment": intent.environment,
                "capability_version": "mcp-proxy/v1",
            },
            "credential_ref": MCP_CREDENTIAL_REF,
            "execution_plan": {
                "adapter": "mcp_proxy",
                "operation": tool_name,
                "target": {"tool_name": tool_name},
                "arguments": arguments,
            },
        }
        plan_canonical = canonical_json(plan_document)
        reserve_usage_meter(self._db, intent.project_id, METER_RUNNER_EXECUTIONS)
        row = ActionExecutionAttempt(
            project_id=intent.project_id,
            action_intent_id=intent.id,
            runner_id=runner_id,
            attempt_number=attempt_number,
            idempotency_key=_attempt_idempotency_key(intent.id, event_id),
            status=final_status,
            credential_ref=MCP_CREDENTIAL_REF,
            plan_digest=sha256_digest(plan_canonical),
            plan_json=plan_canonical,
            result_summary_json=_json_dumps(
                {
                    "source": "mcp_proxy",
                    "execution_state": execution_state,
                    "tool_name": tool_name,
                    "upstream_result": upstream_result,
                    "upstream_error": upstream_error,
                }
            ),
            protected_credential_returned=False,
            requested_by_subject=self._actor,
            started_at=now,
            finished_at=now,
        )
        self._db.add(row)
        self._db.flush()
        record_action_timeline_event(
            self._db,
            project_id=intent.project_id,
            action_id=intent.id,
            event_type="execution_planned",
            payload={
                "source": "mcp_proxy",
                "execution_attempt_id": row.id,
                "runner_id": runner_id,
                "attempt_number": attempt_number,
                "idempotency_key": row.idempotency_key,
                "plan_digest": row.plan_digest,
                "credential_ref": MCP_CREDENTIAL_REF,
            },
            actor=self._actor,
        )
        record_action_timeline_event(
            self._db,
            project_id=intent.project_id,
            action_id=intent.id,
            event_type=f"execution_{final_status}",
            payload={
                "source": "mcp_proxy",
                "execution_attempt_id": row.id,
                "runner_id": runner_id,
                "attempt_number": attempt_number,
                "status": final_status,
                "execution_state": execution_state,
                "error_message": upstream_error,
            },
            actor=self._actor,
        )
        return row


def _attempt_idempotency_key(intent_id: str, event_id: str | None) -> str:
    return f"mcp-execution:{intent_id}:{event_id or 'no-event'}"


def _verification_hint(result: dict[str, Any] | None) -> dict[str, Any]:
    if not isinstance(result, Mapping):
        return {}
    meta = result.get("_meta")
    if not isinstance(meta, Mapping):
        return {}
    zroky = meta.get("zroky")
    if isinstance(zroky, Mapping) and isinstance(zroky.get("verification"), Mapping):
        return dict(zroky["verification"])
    if isinstance(meta.get("verification"), Mapping):
        return dict(meta["verification"])
    return {}


def _actual_record(verification: Mapping[str, Any]) -> dict[str, Any] | None:
    for key in ("actual", "record", "source_record"):
        value = verification.get(key)
        if isinstance(value, Mapping):
            return dict(value)
    return None


def _dict_or(value: Any, fallback: Mapping[str, Any]) -> dict[str, Any]:
    return dict(value) if isinstance(value, Mapping) else dict(fallback)


def _text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _float(value: Any) -> float | None:
    if value is None or isinstance(value, bool):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _string_list(value: Any) -> list[str] | None:
    if not isinstance(value, list | tuple):
        return None
    out = [str(item).strip() for item in value if str(item).strip()]
    return out or None


def _json_dumps(value: Any) -> str:
    return json.dumps(value if value is not None else {}, ensure_ascii=False, allow_nan=False, separators=(",", ":"), sort_keys=True, default=str)
