# !! AUTO-GENERATED by scripts/gen_from_schema.py — DO NOT EDIT BY HAND !!
# Source: api-contracts/ingest-event.schema.json
# Re-generate: python scripts/gen_from_schema.py
from __future__ import annotations

"""OTel span attribute name mapping for IngestEvent fields.

Maps each IngestEvent field name to its OpenTelemetry semantic convention
attribute name. Fields without an OTel mapping are omitted.
Used by the gateway and SDK to emit structured trace attributes.
"""

INGEST_EVENT_OTEL_ATTRIBUTES: dict[str, str] = {
    "call_id": "zroky.call.id",
    "event_id": "zroky.event.id",
    "request_id": "zroky.request.id",
    "provider": "gen_ai.system",
    "model": "gen_ai.response.model",
    "call_type": "zroky.call.type",
    "status": "zroky.call.status",
    "latency_ms": "zroky.call.latency_ms",
    "prompt_tokens": "gen_ai.usage.input_tokens",
    "estimated_prompt_tokens": "zroky.tokens.estimated_prompt",
    "model_context_limit": "zroky.model.context_limit",
    "model_context_limit_source": "zroky.model.context_limit_source",
    "completion_tokens": "gen_ai.usage.output_tokens",
    "reasoning_tokens": "zroky.tokens.reasoning",
    "cache_creation_tokens": "zroky.tokens.cache_creation",
    "cache_read_tokens": "zroky.tokens.cache_read",
    "estimated_cost_usd": "zroky.cost.estimated_usd",
    "actual_cost_usd": "zroky.cost.actual_usd",
    "budget_remaining_usd": "zroky.budget.remaining_usd",
    "budget_action_taken": "zroky.budget.action",
    "loop_action_taken": "zroky.loop.action",
    "loop_call_count": "zroky.loop.call_count",
    "loop_cumulative_cost_usd": "zroky.loop.cumulative_cost_usd",
    "finish_reason": "gen_ai.response.finish_reasons",
    "output_fingerprint": "zroky.output.fingerprint",
    "cache_hit": "zroky.cache.hit",
    "timeout_triggered": "zroky.call.timeout_triggered",
    "resolved_model": "gen_ai.request.model",
    "fallback_attempts": "zroky.fallback.attempts",
    "trace_id": "trace_id",
    "parent_call_id": "zroky.call.parent_id",
    "span_type": "zroky.span.type",
    "span_name": "zroky.span.name",
    "span_index": "zroky.span.index",
    "agent_name": "zroky.agent.name",
    "prompt_fingerprint": "zroky.prompt.fingerprint",
    "prompt_version": "zroky.prompt.version",
    "user_id": "enduser.id",
    "is_synthetic": "zroky.call.is_synthetic",
    "is_production": "zroky.call.is_production",
    "environment": "deployment.environment",
    "metadata": "zroky.metadata",
    "error_code": "zroky.error.code",
    "error_message": "zroky.error.message",
    "session_id": "zroky.session.id",
    "workflow_id": "zroky.workflow.id",
    "workflow_name": "zroky.workflow.name",
    "step_index": "zroky.workflow.step_index",
    "agent_framework": "zroky.agent.framework",
    "capture_source": "zroky.capture.source",
    "masking_version": "zroky.masking.version",
    "pii_masked": "zroky.pii.masked",
}

# Reverse mapping: OTel attribute → IngestEvent field name
OTEL_ATTRIBUTE_TO_FIELD: dict[str, str] = {
    v: k for k, v in INGEST_EVENT_OTEL_ATTRIBUTES.items()
}
