[mypy]
python_version = 3.11
files = app
ignore_missing_imports = True
follow_imports = silent
pretty = True
strict_optional = False
allow_untyped_defs = True
allow_untyped_calls = True
warn_return_any = False
check_untyped_defs = False