[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["/zroky-backend/**"]

[deploy]
startCommand = "sh scripts/start.sh"
healthcheckPath = "/health/live"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
