"""IngestEvent v2 code generator (Rule 1 — ZROKY-005).

Single source of truth: api-contracts/ingest-event.schema.json

Generates (and OVERWRITES) the following artifacts:
  - zroky-backend/app/schemas/ingest_event_v2.py   (Pydantic v2 model)
  - zroky-dashboard/src/lib/ingest-types.ts         (TypeScript interfaces)
  - zroky-backend/app/observability/otel_mapping.py (OTel attribute table)

Run:
    python scripts/gen_from_schema.py

CI drift check (schema-drift-check.yml):
    python scripts/gen_from_schema.py && git diff --exit-code

If the CI job fails, it means a generated artifact is out of sync with the schema.
Re-run this script locally and commit the updated files.

DO NOT hand-edit generated files — changes will be overwritten.
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SCHEMA_PATH = _REPO_ROOT / "api-contracts" / "ingest-event.schema.json"
_PYDANTIC_OUT = _REPO_ROOT / "zroky-backend" / "app" / "schemas" / "ingest_event_v2.py"
_TS_OUT = _REPO_ROOT / "zroky-dashboard" / "src" / "lib" / "ingest-types.ts"
_OTEL_OUT = _REPO_ROOT / "zroky-backend" / "app" / "observability" / "otel_mapping.py"

_GENERATED_HEADER = (
    "# !! AUTO-GENERATED by scripts/gen_from_schema.py — DO NOT EDIT BY HAND !!\n"
    "# Source: api-contracts/ingest-event.schema.json\n"
    "# Re-generate: python scripts/gen_from_schema.py\n"
)

_TS_GENERATED_HEADER = (
    "// !! AUTO-GENERATED by scripts/gen_from_schema.py — DO NOT EDIT BY HAND !!\n"
    "// Source: api-contracts/ingest-event.schema.json\n"
    "// Re-generate: python scripts/gen_from_schema.py\n"
)


# ---------------------------------------------------------------------------
# Schema → type-system mapping helpers
# ---------------------------------------------------------------------------

_JSON_TYPE_TO_PYTHON: dict[str, str] = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "object": "dict[str, Any]",
    "array": "list[Any]",
    "null": "None",
}

_JSON_TYPE_TO_TS: dict[str, str] = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "object": "Record<string, unknown>",
    "array": "unknown[]",
    "null": "null",
}


def _py_type(prop: dict[str, Any]) -> str:
    """Derive a Python type annotation from a JSON Schema property definition."""
    type_val = prop.get("type")
    items = prop.get("items")
    one_of = prop.get("oneOf")

    if one_of:
        parts: list[str] = []
        for sub in one_of:
            t = sub.get("type")
            if t and t != "null":
                parts.append(_JSON_TYPE_TO_PYTHON.get(t, "Any"))
        if any(s.get("type") == "null" for s in one_of):
            return f"{' | '.join(parts)} | None"
        return " | ".join(parts) or "Any"

    if isinstance(type_val, list):
        non_null = [t for t in type_val if t != "null"]
        nullable = "null" in type_val
        if len(non_null) == 1:
            t = non_null[0]
            if t == "array" and items:
                item_t = _JSON_TYPE_TO_PYTHON.get(items.get("type", "object"), "Any")
                base = f"list[{item_t}]"
            else:
                base = _JSON_TYPE_TO_PYTHON.get(t, "Any")
            return f"{base} | None" if nullable else base
        return "Any"

    if isinstance(type_val, str):
        if type_val == "array" and items:
            item_t = _JSON_TYPE_TO_PYTHON.get(items.get("type", "object"), "Any")
            return f"list[{item_t}]"
        return _JSON_TYPE_TO_PYTHON.get(type_val, "Any")

    return "Any"


def _ts_type(prop: dict[str, Any]) -> str:
    """Derive a TypeScript type from a JSON Schema property definition."""
    type_val = prop.get("type")
    items = prop.get("items")
    one_of = prop.get("oneOf")

    if one_of:
        parts: list[str] = []
        for sub in one_of:
            t = sub.get("type")
            if t:
                parts.append(_JSON_TYPE_TO_TS.get(t, "unknown"))
        return " | ".join(dict.fromkeys(parts)) or "unknown"

    if isinstance(type_val, list):
        return " | ".join(dict.fromkeys(_JSON_TYPE_TO_TS.get(t, "unknown") for t in type_val))

    if isinstance(type_val, str):
        if type_val == "array" and items:
            item_t = _JSON_TYPE_TO_TS.get(items.get("type", "object"), "unknown")
            return f"{item_t}[]"
        return _JSON_TYPE_TO_TS.get(type_val, "unknown")

    return "unknown"


def _py_default(prop: dict[str, Any]) -> str | None:
    """Return the Python default expression for a property, or None."""
    if "default" in prop:
        d = prop["default"]
        if isinstance(d, bool):
            return "True" if d else "False"
        if isinstance(d, str):
            return repr(d)
        if d is None:
            return "None"
        return str(d)
    type_val = prop.get("type")
    if isinstance(type_val, list) and "null" in type_val:
        return "None"
    if "oneOf" in prop:
        if any(s.get("type") == "null" for s in prop["oneOf"]):
            return "None"
    return None


def _field_kwargs(prop: dict[str, Any]) -> str:
    """Build Field(...) kwargs string from constraints."""
    parts: list[str] = []
    if "minLength" in prop:
        parts.append(f"min_length={prop['minLength']}")
    if "maxLength" in prop:
        parts.append(f"max_length={prop['maxLength']}")
    if "minimum" in prop:
        parts.append(f"ge={prop['minimum']}")
    if "exclusiveMinimum" in prop:
        parts.append(f"gt={prop['exclusiveMinimum']}")
    if "maximum" in prop:
        parts.append(f"le={prop['maximum']}")
    return ", ".join(parts)


# ---------------------------------------------------------------------------
# Pydantic generator
# ---------------------------------------------------------------------------

def _gen_pydantic(schema: dict[str, Any]) -> str:
    props: dict[str, Any] = schema.get("properties", {})
    required_set: set[str] = set(schema.get("required", []))
    lines: list[str] = []

    lines.append(_GENERATED_HEADER)
    lines.append("from __future__ import annotations\n")
    lines.append("from typing import Any\n\n")
    lines.append("from pydantic import BaseModel, ConfigDict, Field, model_validator\n\n\n")

    desc = schema.get("description", "").split(".")[0]
    lines.append(f'class IngestEventV2(BaseModel):\n')
    lines.append(f'    """{desc}."""\n\n')
    lines.append("    model_config = ConfigDict(extra='ignore')\n\n")

    for field_name, prop in props.items():
        py_t = _py_type(prop)
        default = _py_default(prop)
        description = prop.get("description", "")
        field_kw = _field_kwargs(prop)

        # Build Field() call
        if field_name in required_set:
            if field_kw:
                field_str = f"Field({field_kw})"
            else:
                field_str = "Field()"
            line = f"    {field_name}: {py_t} = {field_str}"
        else:
            default_val = default if default is not None else "None"
            if field_kw:
                field_str = f"Field(default={default_val}, {field_kw})"
            else:
                field_str = f"Field(default={default_val})"
            line = f"    {field_name}: {py_t} = {field_str}"

        if description:
            short_desc = description.split("\n")[0].rstrip(".")[:100]
            lines.append(f"    # {short_desc}\n")
        lines.append(line + "\n")

    lines.append("\n    @model_validator(mode='after')\n")
    lines.append("    def _normalize(self) -> 'IngestEventV2':\n")
    lines.append("        if self.call_id:\n")
    lines.append("            self.call_id = self.call_id.strip()\n")
    lines.append("        self.provider = (self.provider or '').strip() or 'unknown'\n")
    lines.append("        self.model = (self.model or '').strip() or 'unknown'\n")
    lines.append("        return self\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# TypeScript generator
# ---------------------------------------------------------------------------

def _gen_typescript(schema: dict[str, Any]) -> str:
    props: dict[str, Any] = schema.get("properties", {})
    required_set: set[str] = set(schema.get("required", []))
    lines: list[str] = []

    lines.append(_TS_GENERATED_HEADER)
    lines.append("\n")

    title = schema.get("title", "IngestEvent")
    short_desc = schema.get("description", "").split(".")[0]
    lines.append(f"/** {short_desc}. */\n")
    lines.append(f"export interface {title}V2 {{\n")

    for field_name, prop in props.items():
        ts_t = _ts_type(prop)
        description = prop.get("description", "")
        optional = "?" if field_name not in required_set else ""

        if description:
            short = description.split("\n")[0].rstrip(".")[:120]
            lines.append(f"  /** {short} */\n")
        lines.append(f"  {field_name}{optional}: {ts_t};\n")

    lines.append("}\n\n")

    # Convenience type alias for v1 compat
    lines.append("/** Alias for backward compatibility. Prefer IngestEventV2. */\n")
    lines.append(f"export type IngestEvent = {title}V2;\n\n")

    # Enum constant for call_type
    call_type_prop = props.get("call_type", {})
    if "enum" in call_type_prop:
        lines.append("export const CALL_TYPES = [\n")
        for v in call_type_prop["enum"]:
            if v is not None:
                lines.append(f"  '{v}',\n")
        lines.append("] as const;\n\n")
        lines.append("export type CallType = (typeof CALL_TYPES)[number];\n\n")

    # Enum constant for status
    status_prop = props.get("status", {})
    if "enum" in status_prop:
        lines.append("export const CALL_STATUSES = [\n")
        for v in status_prop["enum"]:
            if v is not None:
                lines.append(f"  '{v}',\n")
        lines.append("] as const;\n\n")
        lines.append("export type CallStatus = (typeof CALL_STATUSES)[number];\n\n")

    # Agent framework enum
    af_prop = props.get("agent_framework", {})
    if "enum" in af_prop:
        lines.append("export const AGENT_FRAMEWORKS = [\n")
        for v in af_prop["enum"]:
            if v is not None:
                lines.append(f"  '{v}',\n")
        lines.append("] as const;\n\n")
        lines.append("export type AgentFramework = (typeof AGENT_FRAMEWORKS)[number] | null;\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# OTel mapping generator
# ---------------------------------------------------------------------------

def _gen_otel_mapping(schema: dict[str, Any]) -> str:
    props: dict[str, Any] = schema.get("properties", {})
    lines: list[str] = []

    lines.append(_GENERATED_HEADER)
    lines.append("from __future__ import annotations\n\n")
    lines.append('"""OTel span attribute name mapping for IngestEvent fields.\n\n')
    lines.append("Maps each IngestEvent field name to its OpenTelemetry semantic convention\n")
    lines.append("attribute name. Fields without an OTel mapping are omitted.\n")
    lines.append("Used by the gateway and SDK to emit structured trace attributes.\n")
    lines.append('"""\n\n')

    lines.append("INGEST_EVENT_OTEL_ATTRIBUTES: dict[str, str] = {\n")
    for field_name, prop in props.items():
        otel_attr = prop.get("x-otel-attribute")
        if otel_attr:
            lines.append(f'    "{field_name}": "{otel_attr}",\n')
    lines.append("}\n\n")

    lines.append("# Reverse mapping: OTel attribute → IngestEvent field name\n")
    lines.append("OTEL_ATTRIBUTE_TO_FIELD: dict[str, str] = {\n")
    lines.append("    v: k for k, v in INGEST_EVENT_OTEL_ATTRIBUTES.items()\n")
    lines.append("}\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    if not _SCHEMA_PATH.exists():
        print(f"ERROR: schema not found at {_SCHEMA_PATH}")
        return 1

    with _SCHEMA_PATH.open(encoding="utf-8") as f:
        schema: dict[str, Any] = json.load(f)

    props_count = len(schema.get("properties", {}))
    print(f"gen_from_schema: loaded {_SCHEMA_PATH.relative_to(_REPO_ROOT).as_posix()} ({props_count} properties)")

    pydantic_src = _gen_pydantic(schema)
    _PYDANTIC_OUT.parent.mkdir(parents=True, exist_ok=True)
    _PYDANTIC_OUT.write_text(pydantic_src, encoding="utf-8")
    print(f"  wrote {_PYDANTIC_OUT.relative_to(_REPO_ROOT).as_posix()} ({len(pydantic_src)} bytes)")

    ts_src = _gen_typescript(schema)
    _TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    _TS_OUT.write_text(ts_src, encoding="utf-8")
    print(f"  wrote {_TS_OUT.relative_to(_REPO_ROOT).as_posix()} ({len(ts_src)} bytes)")

    otel_src = _gen_otel_mapping(schema)
    _OTEL_OUT.parent.mkdir(parents=True, exist_ok=True)
    _OTEL_OUT.write_text(otel_src, encoding="utf-8")
    print(f"  wrote {_OTEL_OUT.relative_to(_REPO_ROOT).as_posix()} ({len(otel_src)} bytes)")

    print("Done. Commit all modified files. CI drift check: git diff --exit-code")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
