// !! AUTO-GENERATED by scripts/gen_from_schema.py — DO NOT EDIT BY HAND !!
// Source: api-contracts/ingest-event.schema.json
// Re-generate: python scripts/gen_from_schema.py

/** Canonical schema for a single AI call event ingested by Zroky. */
export interface IngestEventV2 {
  /** Schema version tag. Must be 'v2' for v2 events. Absence implies v1 (treated as v2-compatible) */
  schema_version?: string;
  /** Unique identifier for this AI call. Set by the SDK before send */
  call_id: string;
  /** Optional idempotency key for deduplication */
  event_id?: string | null;
  /** Provider-assigned request ID, if available */
  request_id?: string | null;
  /** AI provider name (e.g. 'openai', 'anthropic', 'google') */
  provider?: string;
  /** Model identifier as returned by the provider (e.g. 'gpt-4o', 'claude-3-5-sonnet') */
  model?: string;
  /** Type of AI call */
  call_type?: string;
  /** Outcome status of the call */
  status?: string;
  /** Wall-clock time from request send to response complete, in milliseconds */
  latency_ms?: number | null;
  /** Number of prompt/input tokens consumed */
  prompt_tokens?: number;
  /** SDK-estimated prompt token count (before provider confirmation) */
  estimated_prompt_tokens?: number | null;
  /** Total context window size of the model, in tokens */
  model_context_limit?: number | null;
  model_context_limit_source?: string | null;
  model_context_limit_source_detail?: string | null;
  model_context_limit_confidence?: number | null;
  model_context_limit_catalog_version?: string | null;
  model_context_limit_catalog_updated_at?: string | null;
  model_context_limit_catalog_stale?: boolean | null;
  model_context_limit_catalog_stale_after_days?: number | null;
  token_estimator_version?: string | null;
  token_rules_version?: string | null;
  /** Number of completion/output tokens generated */
  completion_tokens?: number;
  /** Number of reasoning tokens (e.g. o1 thinking tokens) */
  reasoning_tokens?: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  /** SDK-estimated cost in USD */
  estimated_cost_usd?: number | null;
  /** Provider-billed cost in USD, if available */
  actual_cost_usd?: number | null;
  budget_remaining_usd?: number | null;
  budget_action_taken?: string | null;
  loop_action_taken?: string | null;
  loop_call_count?: number;
  loop_cumulative_cost_usd?: number | null;
  exchange_rate_usd_to_inr?: number | null;
  exchange_rate_timestamp?: number | string | null;
  exchange_rate_source?: string | null;
  /** Tool schemas available to the model for this call */
  tool_definitions?: unknown[] | null;
  /** Tool invocations emitted by the model in this call */
  tool_calls_made?: unknown[] | null;
  /** Normalized/cleaned model output (PII masked) */
  normalized_output?: string | null;
  /** Raw model output content (PII masked) */
  output_content?: string | null;
  /** Stable hash of the output (excluding variable content) */
  output_fingerprint?: string | null;
  tool_lifecycle_summary?: unknown[] | null;
  retry_metadata?: Record<string, unknown> | null;
  cache_hit?: boolean;
  timeout_triggered?: boolean;
  /** Actual model used after fallback resolution, if different from 'model' */
  resolved_model?: string | null;
  /** Ordered list of models tried before success */
  fallback_chain?: unknown[] | null;
  fallback_attempts?: number;
  /** Models whose circuit breakers were open at call time */
  circuit_open_models?: unknown[] | null;
  /** Distributed trace identifier (W3C traceparent format recommended) */
  trace_id?: string | null;
  /** call_id of the parent call in a multi-agent tree */
  parent_call_id?: string | null;
  /** Logical name of the agent making this call */
  agent_name?: string | null;
  /** Stable hash of the prompt template (excluding variable/user content) */
  prompt_fingerprint?: string | null;
  user_id?: string | null;
  /** True for replay or test calls; excluded from cost aggregations */
  is_synthetic?: boolean;
  is_production?: boolean | null;
  /** Runtime environment tag (e.g. 'production', 'staging', 'development') */
  environment?: string | null;
  /** Arbitrary key-value pairs for custom context. Not indexed */
  metadata?: Record<string, unknown> | null;
  /** Structured error/failure code (e.g. 'LOOP_DETECTED', 'BUDGET_EXCEEDED', 'CONTEXT_OVERFLOW') */
  error_code?: string | null;
  error_message?: string | null;
  /** Structured failure diagnostics set by the diagnosis engine */
  failure_reason?: Record<string, unknown> | null;
  /** Unix timestamp (float) or ISO-8601 string of when the call completed */
  created_at?: number | string | null;
  /** [v2] Multi-turn session identifier. Groups calls within a single conversation */
  session_id?: string | null;
  /** [v2] Parent workflow or pipeline run identifier. Groups calls across agent steps */
  workflow_id?: string | null;
  /** [v2] Zero-based step position within a workflow. Used for ordering and cross-step loop detection */
  step_index?: number | null;
  /** [v2] Agent orchestration framework, if known */
  agent_framework?: string | null;
}

/** Alias for backward compatibility. Prefer IngestEventV2. */
export type IngestEvent = IngestEventV2;

export const CALL_TYPES = [
  'chat',
  'completion',
  'embedding',
  'streaming',
  'image',
  'tts',
  'stt',
  'moderation',
  'function',
] as const;

export type CallType = (typeof CALL_TYPES)[number];

export const CALL_STATUSES = [
  'completed',
  'error',
  'timeout',
  'cancelled',
  'rate_limited',
  'budget_blocked',
] as const;

export type CallStatus = (typeof CALL_STATUSES)[number];

export const AGENT_FRAMEWORKS = [
  'langgraph',
  'crewai',
  'autogen',
  'llamaindex',
  'langchain',
  'custom',
] as const;

export type AgentFramework = (typeof AGENT_FRAMEWORKS)[number] | null;
