# !! AUTO-GENERATED by scripts/gen_from_schema.py — DO NOT EDIT BY HAND !!
# Source: api-contracts/ingest-event.schema.json
# Re-generate: python scripts/gen_from_schema.py
from __future__ import annotations
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, model_validator


class IngestEventV2(BaseModel):
    """Canonical schema for a single AI call event ingested by Zroky."""

    model_config = ConfigDict(extra='ignore')

    # Schema version tag. Must be 'v2' for v2 events. Absence implies v1 (treated as v2-compatible)
    schema_version: str = Field(default='v2')
    # Unique identifier for this AI call. Set by the SDK before send
    call_id: str = Field(min_length=1, max_length=64)
    # Optional idempotency key for deduplication
    event_id: str | None = Field(default=None, max_length=128)
    # Provider-assigned request ID, if available
    request_id: str | None = Field(default=None, max_length=128)
    # AI provider name (e.g. 'openai', 'anthropic', 'google')
    provider: str = Field(default='unknown', min_length=1, max_length=120)
    # Model identifier as returned by the provider (e.g. 'gpt-4o', 'claude-3-5-sonnet')
    model: str = Field(default='unknown', min_length=1, max_length=120)
    # Type of AI call
    call_type: str = Field(default='chat')
    # Outcome status of the call
    status: str = Field(default='completed')
    # Wall-clock time from request send to response complete, in milliseconds
    latency_ms: float | None = Field(default=None, ge=0)
    # Number of prompt/input tokens consumed
    prompt_tokens: int = Field(default=0, ge=0)
    # SDK-estimated prompt token count (before provider confirmation)
    estimated_prompt_tokens: int | None = Field(default=None, ge=0)
    # Total context window size of the model, in tokens
    model_context_limit: int | None = Field(default=None, ge=1)
    model_context_limit_source: str | None = Field(default=None, max_length=64)
    model_context_limit_source_detail: str | None = Field(default=None, max_length=128)
    model_context_limit_confidence: float | None = Field(default=None, ge=0, le=1)
    model_context_limit_catalog_version: str | None = Field(default=None, max_length=64)
    model_context_limit_catalog_updated_at: str | None = Field(default=None, max_length=32)
    model_context_limit_catalog_stale: bool | None = Field(default=None)
    model_context_limit_catalog_stale_after_days: int | None = Field(default=None, ge=1)
    token_estimator_version: str | None = Field(default=None, max_length=64)
    token_rules_version: str | None = Field(default=None, max_length=64)
    # Number of completion/output tokens generated
    completion_tokens: int = Field(default=0, ge=0)
    # Number of reasoning tokens (e.g. o1 thinking tokens)
    reasoning_tokens: int = Field(default=0, ge=0)
    cache_creation_tokens: int = Field(default=0, ge=0)
    cache_read_tokens: int = Field(default=0, ge=0)
    # SDK-estimated cost in USD
    estimated_cost_usd: float | None = Field(default=None, ge=0)
    # Provider-billed cost in USD, if available
    actual_cost_usd: float | None = Field(default=None, ge=0)
    budget_remaining_usd: float | None = Field(default=None, ge=0)
    budget_action_taken: str | None = Field(default=None, max_length=64)
    loop_action_taken: str | None = Field(default=None, max_length=64)
    loop_call_count: int = Field(default=0, ge=0)
    loop_cumulative_cost_usd: float | None = Field(default=None, ge=0)
    exchange_rate_usd_to_inr: float | None = Field(default=None, gt=0)
    exchange_rate_timestamp: float | str | None = Field(default=None)
    exchange_rate_source: str | None = Field(default=None, max_length=64)
    # Tool schemas available to the model for this call
    tool_definitions: list[dict[str, Any]] | None = Field(default=None)
    # Canonical tool invocations emitted by the model or captured as tool spans
    tool_calls: list[dict[str, Any]] | None = Field(default=None)
    # Deprecated alias for tool_calls. Accepted for backward compatibility
    tool_calls_made: list[dict[str, Any]] | None = Field(default=None)
    # Structured retrieval/RAG evidence for retrieval spans
    retrieval: dict[str, Any] | None = Field(default=None)
    # Structured task or business outcome signal linked to this call
    outcome: dict[str, Any] | None = Field(default=None)
    # Normalized/cleaned model output (PII masked)
    normalized_output: str | None = Field(default=None, max_length=4000)
    # Raw model output content (PII masked)
    output_content: str | None = Field(default=None, max_length=4000)
    # Provider termination reason for generated output (e.g. stop, length, tool_calls)
    finish_reason: str | None = Field(default=None, max_length=64)
    # Provider stop reason alias, especially for Anthropic streams (e.g. end_turn, max_tokens)
    stop_reason: str | None = Field(default=None, max_length=64)
    # Stable hash of the output (excluding variable content)
    output_fingerprint: str | None = Field(default=None, max_length=64)
    tool_lifecycle_summary: list[dict[str, Any]] | None = Field(default=None)
    retry_metadata: dict[str, Any] | None = Field(default=None)
    cache_hit: bool = Field(default=False)
    timeout_triggered: bool = Field(default=False)
    # Actual model used after fallback resolution, if different from 'model'
    resolved_model: str | None = Field(default=None, max_length=120)
    # Ordered list of models tried before success
    fallback_chain: list[str] | None = Field(default=None)
    fallback_attempts: int = Field(default=0, ge=0)
    # Models whose circuit breakers were open at call time
    circuit_open_models: list[str] | None = Field(default=None)
    # Distributed trace identifier (W3C traceparent format recommended)
    trace_id: str | None = Field(default=None, max_length=128)
    # call_id of the parent call in a multi-agent tree
    parent_call_id: str | None = Field(default=None, max_length=128)
    # [v2] Normalized trace graph span type
    span_type: str | None = Field(default=None, max_length=64)
    # [v2] Human-readable trace graph span name
    span_name: str | None = Field(default=None, max_length=255)
    # [v2] Stable sibling ordering for spans emitted from the same run
    span_index: int | None = Field(default=None, ge=0)
    # [v2] Masked structured input evidence for the span
    input: dict[str, Any] | None = Field(default=None)
    # [v2] Masked system prompt or policy prompt active for this span
    system_prompt: str | None = Field(default=None, max_length=12000)
    # [v2] Masked user input that triggered the span
    user_input: str | None = Field(default=None, max_length=12000)
    # [v2] Masked final answer or tool-visible output for this span
    final_answer: str | None = Field(default=None, max_length=12000)
    # [v2] Masked tool call evidence, including name, arguments, result, and error when available
    tool: dict[str, Any] | None = Field(default=None)
    # [v2] Masked memory read/write evidence for memory spans
    memory: dict[str, Any] | None = Field(default=None)
    # [v2] Masked agent-to-agent handoff evidence
    handoff: dict[str, Any] | None = Field(default=None)
    # [v2] Captured policy decision evidence. Runtime enforcement is out of scope for this schema
    policy: dict[str, Any] | None = Field(default=None)
    # [v2] Version metadata such as code_sha, deployment_id, model_version, tool_schema_version, and rag_v
    versions: dict[str, Any] | None = Field(default=None)
    # Logical name of the agent making this call
    agent_name: str | None = Field(default=None, max_length=255)
    # Stable hash of the prompt template (excluding variable/user content)
    prompt_fingerprint: str | None = Field(default=None, max_length=64)
    # Human-readable or deploy-system prompt version tag (e.g. support-v42, git SHA, release ID)
    prompt_version: str | None = Field(default=None, max_length=128)
    user_id: str | None = Field(default=None, max_length=255)
    # True for replay or test calls; excluded from cost aggregations
    is_synthetic: bool = Field(default=False)
    is_production: bool | None = Field(default=None)
    # Runtime environment tag (e.g. 'production', 'staging', 'development')
    environment: str | None = Field(default=None, max_length=64)
    # Arbitrary key-value pairs for custom context. Not indexed
    metadata: dict[str, Any] | None = Field(default=None)
    # Structured error/failure code (e.g. 'LOOP_DETECTED', 'BUDGET_EXCEEDED', 'CONTEXT_OVERFLOW')
    error_code: str | None = Field(default=None, max_length=120)
    error_message: str | None = Field(default=None, max_length=4000)
    # Structured failure diagnostics set by the diagnosis engine
    failure_reason: dict[str, Any] | None = Field(default=None)
    # Unix timestamp (float) or ISO-8601 string of when the call completed
    created_at: float | str | None = Field(default=None)
    # [v2] Multi-turn session identifier. Groups calls within a single conversation
    session_id: str | None = Field(default=None, max_length=128)
    # [v2] Parent workflow or pipeline run identifier. Groups calls across agent steps
    workflow_id: str | None = Field(default=None, max_length=128)
    # [v2] Human-readable workflow, graph, or pipeline name
    workflow_name: str | None = Field(default=None, max_length=255)
    # [v2] Zero-based step position within a workflow. Used for ordering and cross-step loop detection
    step_index: int | None = Field(default=None, ge=0)
    # [v2] Agent orchestration framework, if known
    agent_framework: str | None = Field(default=None, max_length=64)
    # [v2] Capture surface that emitted this event, such as python_sdk, js_sdk, gateway, or direct_ingest
    capture_source: str | None = Field(default=None, max_length=64)
    # [v2] Redaction/masking rule version applied before ingest
    masking_version: str | None = Field(default=None, max_length=64)
    # [v2] True when the emitter applied PII/secrets masking before sending the event
    pii_masked: bool | None = Field(default=None)

    @model_validator(mode='after')
    def _normalize(self) -> 'IngestEventV2':
        if self.call_id:
            self.call_id = self.call_id.strip()
        self.provider = (self.provider or '').strip() or 'unknown'
        self.model = (self.model or '').strip() or 'unknown'
        return self
